
name: Build Android APK

permissions:
  contents: write

on:
  push:
    branches: [ main, master ]
    paths:
      - 'music/**'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
        channel: 'stable'

    - name: Flutter doctor
      working-directory: ./music
      run: flutter doctor -v

    - name: Get Flutter dependencies
      working-directory: ./music
      run: flutter pub get

    - name: Flutter clean
      working-directory: ./music
      run: flutter clean

    - name: Build APK
      working-directory: ./music
      run: flutter build apk --release --no-shrink

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: music-player-apk
        path: music/build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Music Player v${{ github.run_number }}
        body: |
          Music Player Android App - Release Build

          ## Features
          - Clean, modern music player interface
          - Local music file playback
          - Beautiful UI design
          - Smooth performance

          ## Installation
          1. Download APK file below
          2. Enable "Install from unknown sources" in Android settings
          3. Install APK on Android device
          4. Grant storage permissions when prompted

        files: music/build/app/outputs/flutter-apk/app-release.apk
        github_token: ${{ secrets.GITHUB_TOKEN }}
